### ISSUE TITLE
c1bccecf7 broke templates

### ISSUE THREAD

**Issue by geriBatai** [fabric8io/templates#1]
https://github.com/fabric8io/templates/tree/master/default/template contains loads of nginx 404 pages. Looks like templates were scraped from somewhere  automatically and commited back with not founds.

**Comment by rawlingsj** [comment]
Ah thanks for the heads up!  We'll get this sorted.

**Comment by rawlingsj** [comment]
Ok the templates are generating correctly now.. sorry about that!  https://github.com/fabric8io/templates/commit/1d1e1c30d584aa651a1c9331142757a562fe5f10
